# This is a basic workflow to help you get started with Actions

name: CI

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo \Updated in `date +%Y-%m-%d_%H:%M`\ >> log.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update log"
          git push
